// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtPXod-KJ9kJfj7SEy-zBruemlKQtZ1bk',
    appId: '1:366800162664:web:3023b4a53b50f12c2290dd',
    messagingSenderId: '366800162664',
    projectId: 'fireship-e3b87',
    authDomain: 'fireship-e3b87.firebaseapp.com',
    storageBucket: 'fireship-e3b87.firebasestorage.app',
    measurementId: 'G-H3RKYT3NVS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHylkmObOylV2Awe2bszGXsH92eFgsurw',
    appId: '1:366800162664:android:fce79934ce5571bf2290dd',
    messagingSenderId: '366800162664',
    projectId: 'fireship-e3b87',
    storageBucket: 'fireship-e3b87.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp-BhVcVbBQ7hU4EabEqsWudOGFpf20ac',
    appId: '1:366800162664:ios:fa7747450cac59242290dd',
    messagingSenderId: '366800162664',
    projectId: 'fireship-e3b87',
    storageBucket: 'fireship-e3b87.firebasestorage.app',
    androidClientId: '366800162664-me54nakk8f39nl1hd9q978vtccompi0g.apps.googleusercontent.com',
    iosClientId: '366800162664-kco4unlgn8u3pq1u47i9d96gmasq5mf4.apps.googleusercontent.com',
    iosBundleId: 'io.fireship.fireship',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBp-BhVcVbBQ7hU4EabEqsWudOGFpf20ac',
    appId: '1:366800162664:ios:fa7747450cac59242290dd',
    messagingSenderId: '366800162664',
    projectId: 'fireship-e3b87',
    storageBucket: 'fireship-e3b87.firebasestorage.app',
    androidClientId: '366800162664-me54nakk8f39nl1hd9q978vtccompi0g.apps.googleusercontent.com',
    iosClientId: '366800162664-kco4unlgn8u3pq1u47i9d96gmasq5mf4.apps.googleusercontent.com',
    iosBundleId: 'io.fireship.fireship',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtPXod-KJ9kJfj7SEy-zBruemlKQtZ1bk',
    appId: '1:366800162664:web:50f9590b18dbba082290dd',
    messagingSenderId: '366800162664',
    projectId: 'fireship-e3b87',
    authDomain: 'fireship-e3b87.firebaseapp.com',
    storageBucket: 'fireship-e3b87.firebasestorage.app',
    measurementId: 'G-RP8MD9PHV9',
  );
}
